### ISSUE TITLE
Open Redirect Vulnerability - /redir?choice=

### ISSUE THREAD

**Issue by iamaldi** [TsimpDim/NewsCollector#3]
Hi @TsimpDim ,

Reproduction of the vulnerability

1. Navigate to http://newscollectorapp.azurewebsites.net/redir?choice=//google.com
2. Notice that you're being redirected to https://www.google.com

Vulnerable URL Parameter

The 'choice' URL is vulnerable to Open Redirect. By using Relative Path URLs it is possible to make redirects outside the application's scope, i.e on another domain like google.com.

Vulnerable code:
`app.get('/redir' , function(request,response){`
`     response.redirect('/'+request.query['choice'])`
`});`

Whatever value the 'choice' parameter contains it is going to it pass to the redirect() method, thus redirecting the user to an arbitrary external domain.

More on Open Redirects: https://www.owasp.org/index.php/Top_10_2013-A10-Unvalidated_Redirects_and_Forwards

**Comment by TsimpDim** [comment]
Issue closed. Check out pull requests #4 and #5
